version: '3.7'

services:
  fusion-hbar-service-backend:
    image: ${DOCKER_PREFIX:-ifx40}/fusion-hbar-service-backend:${DOCKER_TAG:-latest}
    build:
      context: ./backend
      args:
        ENV: dev #set to dev for testing in prod AWS cluster; change to prod whenever necessary
    ports:
    - "4021:4021"
